version: "3"

services:
  test:
    build: .
    pull_policy: build
    environment:
    - DISPLAY
    volumes:
    - "/tmp/.X11-unix:/tmp/.X11-unix"
    - "/dev/snd:/dev/snd"
    depends_on:
    - testbox
