[tool.black]
line-length = 120
skip-string-normalization = true
include = "\\.py$"

[tool.poetry]
name = "ultima6-ru"
version = "0.1.0"
description = ""
authors = []

[tool.poetry.dependencies]
python = "^3.11"
pillow = "^10.3.0"

