name: Build

on:
  push:
    branches: [master]

  pull_request:
    branches: [master]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
        - patch: russian
          data: russian
        - patch: english
          data: russian
        - patch: english
          data: english

    name: patch=${{ matrix.patch }}, data=${{ matrix.data }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Build
      id: build
      run: |
        sudo apt-get install nasm
        pip3 install poetry
        poetry config virtualenvs.create false
        poetry install
        python3 -m tools.build ${{ matrix.patch }} ${{ matrix.data }}

    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        name: "${{ steps.build.outputs.basename }}"
        path: "*.zip"
        if-no-files-found: error
