name: Build

on:
  push:
    branches: [master]

  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Build
      run: |
        sudo apt-get install nasm
        python3 -m tools.build

    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        name: UltimaVI-ru
        path: UltimaVI-ru-*.zip
        if-no-files-found: error
