name: Build

on:
  push:
    branches: [master]

  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Build
      run: |
        sudo apt install nasm
        python3 tools/build.py
    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        name: UltimaIV-ru
        path: UltimaIV-ru-*.zip
        if-no-files-found: error
