name: Build

on:
  push:
    branches: [master]

  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Build
      run: |
        sudo apt install nasm
        export PYTHONPATH=${{ github.workspace }}:$PYTHONPATH
        python3 -m tools.build

    - name: Test
      run: |
        docker-compose -f docker-compose.console.yml build test
        docker-compose -f docker-compose.console.yml run test

    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        name: UltimaVI-ru
        path: UltimaVI-ru-*.zip
        if-no-files-found: error
