name: Test

on:
  push:
    branches: [master]

  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Test
      run: |
        docker-compose -f docker-compose.console.yml build test
        docker-compose -f docker-compose.console.yml run test
