name: Translation

on:
  push:
    branches: [master]

  pull_request:
    branches: [master]

jobs:
  translation:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Check with `translation`
      run: |
        export PYTHONPATH=${{ github.workspace }}:$PYTHONPATH
        python3 -m tools.translation

    - name: Check with `duplicates`
      run: |
        export PYTHONPATH=${{ github.workspace }}:$PYTHONPATH
        python3 -m tools.duplicates
